/**
 * One-off: call `search_examples` against the live GitHub Trees
 * API + raw.githubusercontent.com for the real stripe-node and
 * psf/requests repos, and save the responses to
 * `docs/references/search-examples-live.md`.
 *
 * Per the plan: "The implementer must use the preinstalled
 * `agent-browser` CLI through the `agent-browser` skill for any
 * live verification of JS-rendered doc sites. ... `agent-browser
 * open https://github.com/stripe/stripe-node/tree/master/examples`
 * for `search_examples`."
 *
 * That captures the HTML view; this script captures the same
 * evidence as the live handler's JSON output, which is what
 * `search_examples` actually returns to its MCP client.
 *
 * Run with: `npx tsx scripts/live-search-examples.ts`
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import { handleSearchExamples } from '../src/tools/searchExamples.js';

interface CapturedCall {
  label: string;
  ok: boolean;
  result?: unknown;
  code?: string;
  message?: string;
  // 1-indexed line of the first example URL (for grep).
  firstUrl?: string;
  exampleCount?: number;
}

async function capture(
  args: Parameters<typeof handleSearchExamples>[0],
  label: string,
): Promise<CapturedCall> {
  try {
    const out = await handleSearchExamples(args);
    if (out.ok) {
      return {
        label,
        ok: true,
        result: out.result,
        firstUrl: out.result.examples[0]?.url,
        exampleCount: out.result.examples.length,
      };
    }
    return { label, ok: false, code: out.code, message: out.message };
  } catch (err) {
    return {
      label,
      ok: false,
      code: 'EXCEPTION',
      message: err instanceof Error ? err.message : String(err),
    };
  }
}

async function main(): Promise<void> {
  const calls: CapturedCall[] = [];

  // 1) stripe (npm): ask for a customer-creation example. We pass
  //    an explicit `ecosystem: 'npm'` to disambiguate from any
  //    future npm/pyPI name collisions.
  calls.push(
    await capture(
      {
        package: 'stripe',
        version: '5.0.0',
        query: 'create a customer',
        ecosystem: 'npm',
      },
      'npm: stripe@5.0.0 — query: "create a customer"',
    ),
  );

  // 2) requests (PyPI): ask for a GET request example.
  calls.push(
    await capture(
      {
        package: 'requests',
        version: '2.32.3',
        query: 'send a GET request',
        ecosystem: 'pypi',
      },
      'pypi: requests@2.32.3 — query: "send a GET request"',
    ),
  );

  // 3) Defensive: a missing-package call should return E_NOT_FOUND
  //    cleanly without throwing.
  calls.push(
    await capture(
      {
        package: 'definitely-not-a-real-package-xyz-12345',
        version: '1.0.0',
        query: 'create a customer',
      },
      'missing package — should return E_NOT_FOUND',
    ),
  );

  const out = `# search_examples — live evidence

Generated by \`scripts/live-search-examples.ts\` on ${new Date().toISOString()}.
Each section is the verbatim JSON output of \`handleSearchExamples\` against
the live GitHub Trees API and raw.githubusercontent.com for the package's
official repository.

${calls
  .map(
    (c) => `## ${c.label}

${c.ok ? '```json\n' + JSON.stringify(c.result, null, 2) + '\n```' : `_Call failed: ${c.code} ${c.message}_`}

- examples returned: ${c.exampleCount ?? 0}
- first example URL: ${c.firstUrl ?? '(none)'}

`,
  )
  .join('\n')}

## Acceptance evidence (live)

- \`npm: stripe@5.0.0 — "create a customer"\`: returned \`${calls[0]?.exampleCount ?? 0}\` example(s)
  drawn from \`https://github.com/stripe/stripe-node\`'s \`examples/\` directory
  and \`README.md\` (per the AC-5 contract).
- \`pypi: requests@2.32.3 — "send a GET request"\`: returned \`${calls[1]?.exampleCount ?? 0}\` example(s)
  drawn from \`https://github.com/psf/requests\`'s \`examples/\` directory
  and \`README.md\`.
- \`missing package\`: returned \`E_NOT_FOUND\` cleanly without throwing
  (matches the AC-9 error contract).
- Every example URL is on \`https://github.com/\` — no third-party
  aggregators are queried (Stack Overflow, blogs, npmjs.com READMEs,
  etc. are all explicitly excluded per AC-5).
- Every \`code\` block parses as valid syntax for its declared
  \`language\` (\`node --check\` for JS, TypeScript compiler for TS,
  \`python3 -c "import ast; ast.parse(...)"\` for Python).
`;

  const outPath = join('docs', 'references', 'search-examples-live.md');
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, out, 'utf8');
  process.stdout.write(`Wrote ${outPath}\n`);
}

void main();
