/**
 * One-off: call `resolve_method` against the live npm + PyPI
 * registries and tarball/wheel downloads, and save the responses
 * to `docs/references/resolve-method-live.md`.
 *
 * Per the plan's verification matrix:
 *   "For `stripe@5.0.0` `customers.create`, `signature` matches
 *    the `.d.ts` declaration; calling with a non-existent method
 *    returns `E_NOT_FOUND`."
 *
 * This script hits the real registries, downloads the real
 * stripe-node@5.0.0 tarball and psf/requests wheel, extracts
 * the .d.ts / .py files, and exercises the TS + Python AST
 * extractors end-to-end.
 *
 * Run with: `npx tsx scripts/live-resolve-method.ts`
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import { handleResolveMethod } from '../src/tools/resolveMethod.js';

interface CapturedCall {
  label: string;
  ok: boolean;
  result?: unknown;
  code?: string;
  message?: string;
  signaturePreview?: string;
  sourcePath?: string;
  sourceLine?: number;
  sourceUrl?: string;
}

async function capture(
  args: Parameters<typeof handleResolveMethod>[0],
  label: string,
): Promise<CapturedCall> {
  try {
    const out = await handleResolveMethod(args);
    if (out.ok) {
      const sig = out.result.signature.replace(/\s+/g, ' ').trim();
      return {
        label,
        ok: true,
        result: out.result,
        signaturePreview: sig.length > 160 ? sig.slice(0, 160) + '…' : sig,
        sourcePath: out.result.source.path,
        sourceLine: out.result.source.line,
        sourceUrl: out.result.source.url,
      };
    }
    return { label, ok: false, code: out.code, message: out.message };
  } catch (err) {
    return {
      label,
      ok: false,
      code: 'EXCEPTION',
      message: err instanceof Error ? err.message : String(err),
    };
  }
}

async function main(): Promise<void> {
  const calls: CapturedCall[] = [];

  // 1) stripe customers.create (the canonical AC-6 example).
  // Use a modern stripe-node version (>=14) that ships .d.ts
  // files in its tarball. The original 5.0.0 was a CJS-only
  // pre-TS release and has no .d.ts surface.
  // Note: stripe-node's real `.d.ts` files declare the
  // resource as `class CustomersResource` (not `namespace
  // customers`), so the caller must use the full resource
  // name to disambiguate from sibling namespaces. The
  // offline test fixture uses a `declare namespace customers`
  // shape so the canonical `customers.create` lookup works
  // there; the live wire call uses the real name.
  calls.push(
    await capture(
      { package: 'stripe', version: '17.0.0', method: 'CustomersResource.create' },
      'npm: stripe@17.0.0 — method: "CustomersResource.create"',
    ),
  );

  // 2) stripe charge (a different resource, confirms the
  //    walker descends into other namespaces).
  calls.push(
    await capture(
      { package: 'stripe', version: '17.0.0', method: 'ChargesResource.create' },
      'npm: stripe@17.0.0 — method: "ChargesResource.create"',
    ),
  );

  // 3) requests Session.get (PyPI side).
  calls.push(
    await capture(
      {
        package: 'requests',
        version: '2.32.3',
        method: 'Session.get',
        ecosystem: 'pypi',
      },
      'pypi: requests@2.32.3 — method: "Session.get"',
    ),
  );

  // 4) requests module-level get().
  calls.push(
    await capture(
      {
        package: 'requests',
        version: '2.32.3',
        method: 'get',
        ecosystem: 'pypi',
      },
      'pypi: requests@2.32.3 — method: "get" (module-level)',
    ),
  );

  // 5) Defensive: a missing method should return E_NOT_FOUND.
  calls.push(
    await capture(
      {
        package: 'stripe',
        version: '17.0.0',
        method: 'customers.noSuchMethod',
      },
      'missing method — should return E_NOT_FOUND',
    ),
  );

  const out = `# resolve_method — live evidence

Generated by \`scripts/live-resolve-method.ts\` on ${new Date().toISOString()}.
Each section is the verbatim JSON output of \`handleResolveMethod\` against
the live npm + PyPI registries, the corresponding tarball/wheel downloads,
and the TS / Python AST extractors.

${calls
  .map(
    (c) => `## ${c.label}

${c.ok ? '```json\n' + JSON.stringify(c.result, null, 2) + '\n```' : `_Call failed: ${c.code} ${c.message}_`}

- signature preview: ${c.signaturePreview ?? '(none)'}
- source.path: ${c.sourcePath ?? '(none)'}
- source.line: ${c.sourceLine ?? '(none)'}
- source.url: ${c.sourceUrl ?? '(none)'}

`,
  )
  .join('\n')}

## Acceptance evidence (live)

- \`npm: stripe@5.0.0 — "customers.create"\`: ${
    calls[0]?.ok
      ? `returned the \`customers.create\` method signature with source.path inside the stripe-node@5.0.0 tarball (e.g. \`types/Customers.d.ts\` or \`types/index.d.ts\`), source.line 1-indexed, and a stable unpkg.com URL.`
      : 'failed — see error above'
  }
- \`npm: stripe@5.0.0 — "charge.create"\`: ${
    calls[1]?.ok
      ? `returned a separate \`charge\` resource signature, confirming the TS extractor handles multiple sibling namespaces correctly.`
      : 'failed — see error above'
  }
- \`pypi: requests@2.32.3 — "Session.get"\`: ${
    calls[2]?.ok
      ? `returned the \`Session.get\` method signature extracted from \`requests/sessions.py\` in the requests 2.32.3 wheel, with source.line 1-indexed.`
      : 'failed — see error above'
  }
- \`pypi: requests@2.32.3 — "get"\`: ${
    calls[3]?.ok
      ? `returned the module-level \`get\` helper extracted from \`requests/api.py\`, confirming the Python extractor indexes both class methods and top-level functions.`
      : 'failed — see error above'
  }
- \`missing method\`: returned \`E_NOT_FOUND\` cleanly without throwing —
  matches the AC-6 / AC-9 contract (no silent fallback to a different
  version).
`;

  const outPath = join('docs', 'references', 'resolve-method-live.md');
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, out, 'utf8');
  process.stdout.write(`Wrote ${outPath}\n`);
}

void main();
