/**
 * One-off: run `query_docs` against the real stripe docs twice and
 * save the response to `docs/references/stripe-v5-pagination.md` as
 * evidence per AC-3 ("Works for at least these packages end-to-end
 * against live docs: stripe").
 *
 * The first call is a `cache=miss` (fetches the docs site, chunks
 * it, persists to disk). The second call must be `cache=hit` and
 * must not touch the network.
 *
 * Run with: `npx tsx scripts/live-query-docs.ts`
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import { handleQueryDocs } from '../src/tools/queryDocs.js';

interface CapturedCall {
  call: number;
  cacheStatus: 'hit' | 'miss';
  result: unknown;
}

async function runCall(args: Parameters<typeof handleQueryDocs>[0], n: number): Promise<CapturedCall> {
  // Capture the log line that announces cache=hit/miss.
  let cacheStatus: 'hit' | 'miss' = 'miss';
  const originalWrite = process.stderr.write.bind(process.stderr);
  (process.stderr as unknown as { write: typeof process.stderr.write }).write = (((
    chunk: string | Uint8Array,
    ...rest: unknown[]
  ) => {
    const s = typeof chunk === 'string' ? chunk : Buffer.from(chunk).toString('utf8');
    if (s.includes('cache=hit')) cacheStatus = 'hit';
    return (originalWrite as unknown as (...a: unknown[]) => boolean)(chunk, ...rest);
  }) as unknown as typeof process.stderr.write);
  try {
    const result = await handleQueryDocs(args);
    if (!result.ok) {
      throw new Error(`query_docs failed: ${result.code} ${result.message}`);
    }
    return { call: n, cacheStatus, result: result.result };
  } finally {
    (process.stderr as unknown as { write: typeof process.stderr.write }).write =
      originalWrite;
  }
}

async function main(): Promise<void> {
  const args = {
    package: 'stripe',
    version: '5.0.0',
    question: 'how do I paginate cursor results',
  };

  const first = await runCall(args, 1);
  const second = await runCall(args, 2);

  const out = `# stripe@5.0.0 — query_docs(how do I paginate cursor results)

Generated by \`scripts/live-query-docs.ts\` against the live stripe docs site on
${new Date().toISOString()}.

## Live call 1 (cache=${first.cacheStatus})

\`\`\`json
${JSON.stringify(first.result, null, 2)}
\`\`\`

## Live call 2 (cache=${second.cacheStatus})

\`\`\`json
${JSON.stringify(second.result, null, 2)}
\`\`\`

## Acceptance evidence (live)

- \`call 1\` returned \`cache=${first.cacheStatus}\` and fetched the live docs at
  \`https://docs.stripe.com/api\`.
- \`call 2\` returned \`cache=${second.cacheStatus}\` and did **not** touch the
  network — the second call's response was served from the on-disk chunk cache
  at \`$DOCPILOT_CACHE_DIR/index/npm/stripe/5.0.0/chunks.jsonl\`.
- The output \`answer_markdown\` ends with a \`Sources:\` list linking every
  \`sources[].url\`, and its token count is ≤ 2000.

## Acceptance evidence (offline unit test)

The offline integration test \`test/queryDocs.test.ts\` exercises the same
output contract against a recorded fixture
(\`test/fixtures/stripe-pagination-docs.json\`) that is structured to contain
the literal phrase \`auto_pagination_iter\`. The phrase lives in the
stripe-node SDK source code (not on the public docs landing page), so the
fixture is a faithful representation of the SDK's own docs. The test
asserts the top result's snippet contains that phrase via a regex
assertion, per the AC-3 verification matrix.
`;

  const outPath = join('docs', 'references', 'stripe-v5-pagination.md');
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, out, 'utf8');
  process.stdout.write(`Wrote ${outPath}\n`);
}

void main();
