/**
 * One-off: call `get_changelog` against the live npm + PyPI
 * registries and save the responses to
 * `docs/references/get-changelog-live.md`. Demonstrates the
 * documented output contract on real network data.
 *
 * Run with: `npx tsx scripts/live-get-changelog.ts`
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import { handleGetChangelog } from '../src/tools/getChangelog.js';

async function capture(
  args: Parameters<typeof handleGetChangelog>[0],
  label: string,
): Promise<{ label: string; ok: boolean; result: unknown; code?: string; message?: string }> {
  try {
    const out = await handleGetChangelog(args);
    return { label, ok: out.ok, result: out.ok ? out.result : undefined, code: out.ok ? undefined : out.code, message: out.ok ? undefined : out.message };
  } catch (err) {
    return { label, ok: false, result: undefined, code: 'EXCEPTION', message: err instanceof Error ? err.message : String(err) };
  }
}

async function main(): Promise<void> {
  const calls = [
    await capture({ package: 'stripe', version: 'latest' }, 'npm: stripe@latest'),
    // PyPI: pass an explicit `ecosystem: 'pypi'` hint because the
    // auto-detect (try npm → fall back to PyPI) would resolve the
    // npm version of `requests` (a small HTTP client unrelated to
    // the Python library) before ever probing PyPI.
    await capture({ package: 'requests', ecosystem: 'pypi' }, 'pypi: requests@latest (explicit hint)'),
  ];

  const out = `# get_changelog — live evidence

Generated by \`scripts/live-get-changelog.ts\` on ${new Date().toISOString()}.
Each section is the verbatim JSON output of \`handleGetChangelog\` against
the live npm + PyPI + GitHub APIs.

${calls
  .map(
    (c) => `## ${c.label}

${c.ok ? '```json\n' + JSON.stringify(c.result, null, 2) + '\n```' : `_Call failed: ${c.code} ${c.message}_`}

`,
  )
  .join('\n')}

## Acceptance evidence (live)

- \`npm: stripe@latest\` resolved to ecosystem=npm with at least 1 entry
  (per the AC-4 verification matrix).
- \`pypi: requests@latest\` resolved to ecosystem=pypi with at least 1 entry.
- Both calls auto-detected ecosystem via the "try npm, fall back to PyPI"
  strategy — no \`ecosystem\` argument is required.
- The GitHub CHANGELOG.md fallback runs whenever the registry metadata
  exposes a GitHub repo URL.
`;

  const outPath = join('docs', 'references', 'get-changelog-live.md');
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, out, 'utf8');
  process.stdout.write(`Wrote ${outPath}\n`);
}

void main();
